# Generated by Django 3.1.4 on 2022-07-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20220708_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether user the user should be treated as active', verbose_name='Acitve Status'),
        ),
    ]
